export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
export const SEND_REGISTER_REQUEST = "SEND_REGISTER_REQUEST";
export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";
export const INFO = "INFO";
export const CLEAR_ALERT = "CLEAR_ALERT";
